name: Kubernetes

on:
  workflow_call:
  
jobs:

  EKS:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}
        aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}
        aws-region: us-east-2
     
    - run: git clone https://github.com/rodrigosousadf/Infra_CI_Kubernetes.git
     
    - name: HashiCorp - Setup Terraform
      # You may pin to the exact commit or the version.
      # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
      uses: hashicorp/setup-terraform@v2.0.3
      
    - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog init
    #tirar os comentário dos dois abaixo pra atualizar a derrubar o cluster
    #pra não ficar gerando custos na eks. 
    #- run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog destroy -auto-approve
    #- run: return 1
    - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog apply -auto-approve

    - run: echo "$(terraform -chdir=Infra_CI_Kubernetes/env/Homolog output -raw IP_db)"
      id: URL
    
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3
      
    - run: aws sts get-caller-identity
    
    - run: aws eks update-kubeconfig --region us-west-2 --name homolog2
    
    - run: kubectl get svc kubectl delete secret


    - run: kubectl delete secret dbhost --ignore-not-found
    - run: kubectl create secret generic dbhost --from-literal=HOST=${{steps.URL.outputs.stdout}}

    - run: kubectl delete secret dbport --ignore-not-found
    - run: kubectl create secret generic dbport --from-literal=DBPORT=${{secrets.DBPORT}}

    - run: kubectl delete secret dbuser --ignore-not-found
    - run: kubectl create secret generic dbuser --from-literal=USER=${{secrets.DBUSER}}

    - run: kubectl delete secret dbpassword --ignore-not-found
    - run: kubectl create secret generic dbpassword --from-literal=PASSWORD=${{secrets.DBPASSWORD}}

    - run: kubectl delete secret dbname --ignore-not-found
    - run: kubectl create secret generic dbname --from-literal=DBNAME=${{secrets.DBNAME}}

    - run: kubectl delete secret port --ignore-not-found
    - run: kubectl create secret generic port --from-literal=PORT=8000

    #criar depois do segredos pra não correr o risco de iniciar sem segredos

    - run: kubectl apply -f Infra_CI_Kubernetes/go.yml

    - run: kubectl set image deployment/go-api go=rodrigosousadf/go_ci:${{github.run_number}}

    
     
     
        
     
